sudo: false

addons:
  apt:
    packages:
    - python-docutils

language: php
php:
  - 5.5
  - 5.6
  - 7.0
 
matrix:
  allow_failures:
    - php: 7.0
  fast_finish: true

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

script: ./.travis.sh

